name: filename check
on: [pull_request]
jobs:
  filename-check:
    runs-on: ubuntu-latest
    env:
      PATH_REGEX: ^.+\/docs\/.+\/(ja|en)\/section\-[0-9]\/lesson\-[0-9]_.+\.md$
    steps:
      - uses: actions/checkout@v3
      - name: grep invalid filename
        run: |
          ! find ./docs/**/* -maxdepth 3 -type f | grep -Ev $PATH_REGEX
