name: textlint-fix
on:
  workflow_dispatch:
    inputs:
      target_ref:
        description: "Branch to fix"
        required: true
        default: "AVAM-AMM-en"
      scope:
        description: "Glob of files to fix"
        required: false
        default: "docs/Avalanche/AVAX-AMM/en/**/*.md"

permissions:
  contents: write

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable && yarn --frozen-lockfile
      - run: npx textlint --fix "${{ github.event.inputs.scope }}"
      - name: Commit changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore(textlint): auto-fix (${{ github.event.inputs.target_ref }})" || exit 0
          git push origin HEAD:${{ github.event.inputs.target_ref }}
